title: My Project Work
description: A detailed view of my project with documentation and code.
theme: jekyll-theme-cayman
show_downloads: true
google_analytics: 
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
